const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state={done:{},notes:[],theme:'light'},editing=null,filter='全部';try{const saved=JSON.parse(localStorage.getItem('zxy-notes-v1'));if(saved&&saved.done&&Array.isArray(saved.notes))state={...state,...saved}}catch{}
const tracks={rag:{title:'Agentic RAG',desc:'从检索增强生成，到能够规划、检索与自我检查的知识助手。',icon:'◇',phases:[['基础与检索',[['建立 RAG 基线','准备一份小型文档集，串联切分、检索与回答，记录第一版结果。'],['理解检索质量','比较不同切分方式，记录命中情况和引用是否支持回答。']]],['Agent 工作流',[['接入检索工具','让 Agent 根据问题决定是否检索，保留工具调用与中间结果。'],['加入反思与重试','设计停止条件与调用预算，记录失败、重试和最终回答。']]],['评测与迭代',[['建立固定评测集','保存问题、参考证据与评分规则，在相同条件下比较基线。'],['整理项目总结','记录效果、延迟、成本与失败案例，补充运行说明。']]]]},rl:{title:'Agentic RL',desc:'从强化学习基础出发，完成一个可评测、可复现的 Agent 训练实验。',icon:'◈',phases:[['强化学习基础',[['梳理问题定义','理解状态、动作、奖励与策略，用一个小环境描述完整交互过程。'],['选择复现目标','确定论文或项目，记录代码版本、实验目标、算力和依赖。']]],['训练与环境',[['跑通环境与基线','验证环境交互、终止条件和评估脚本，保存未训练策略的结果。'],['完成最小训练实验','用小规模配置验证训练闭环，记录奖励、损失与随机种子。']]],['实验与复现',[['对照与消融','固定评估条件，比较训练前后结果，检验奖励设计或关键模块。'],['完成复现报告','整理配置、曲线、偏差原因与局限，区分原论文结论和自己的结果。']]]]} };
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',2800)}
function save(){try{localStorage.setItem('zxy-notes-v1',JSON.stringify(state));return true}catch{toast('浏览器存储不可用，请导出备份');return false}}
function count(k){return Object.keys(state.done).filter(x=>x.startsWith(k+'-')&&state.done[x]).length}function total(){return count('rag')+count('rl')}
const footer=()=>'<footer><span>© 2026 zxy-note · 学习是一场持续的迭代</span><span>BUILD · LEARN · RECORD</span></footer>';
function renderHeading(title,eyebrow,desc,action=true){return `<div class="crumb">zxy-note <span>/</span> ${title}</div><div class="eyebrow">${eyebrow}</div><div class="heading"><h1>${title}</h1>${action?'<button class="primary" data-new>＋ 写笔记</button>':''}</div><p class="intro">${desc}</p>`}
function card(k){let t=tracks[k],n=count(k);return `<a class="project ${k}" href="#${k}"><div class="project-top"><span class="project-icon">${t.icon}</span><span class="badge">${n===6?'已完成':n?'进行中':'待开始'}</span></div><h3>${t.title}</h3><p>${t.desc}</p><div class="progress-label"><span>学习路线</span><span>${n} / 6 个阶段</span></div><progress value="${n}" max="6" aria-label="${t.title}进度"></progress><div class="project-footer"><span>${k==='rag'?'检索 · 工具调用 · 评测':'环境 · 训练 · 论文复现'}</span><span>进入项目 ↗</span></div></a>`}
function notesView(notes){if(!notes.length)return '<div class="empty"><div><p>把今天的一个收获，留在这里。</p><small class="muted">还没有学习笔记，从第一个问题开始记录。</small></div><button class="secondary" data-new>写第一篇笔记 ↗</button></div>';return notes.map(n=>`<details class="note"><summary><span class="muted">${esc(n.date)}　/　${esc(n.track)}</span><h3>${esc(n.title)} <span class="muted">↗</span></h3></summary><div class="note-content">${esc(n.body)}</div><div class="note-actions"><button class="secondary" data-edit="${esc(n.id)}">编辑</button><button class="secondary" data-delete="${esc(n.id)}">删除</button></div></details>`).join('')}
function render(){let route=location.hash.slice(1)||'overview';if(!['overview','rag','rl','journal','about'].includes(route)){const target=document.getElementById(route);if(target)target.scrollIntoView();return}document.body.classList.toggle('dark',state.theme==='dark');document.querySelectorAll('a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+route));$('.sidebar').classList.remove('open');let html='',toc=[];
if(route==='overview'){html=renderHeading('学习总览','ZXY / AGENT LEARNING JOURNEY','在实践中理解 Agent，在记录中积累自己的知识体系。')+'<div class="meta"><span>◎ 两条学习主线</span><span>↻ 持续更新的个人学习空间</span></div>'+`<div class="stats"><div class="stat"><strong>02</strong><small>条</small><p>项目学习路线</p></div><div class="stat"><strong>${String(total()).padStart(2,'0')}</strong><small>/ 12</small><p>已完成学习阶段</p></div><div class="stat"><strong>${String(state.notes.length).padStart(2,'0')}</strong><small>篇</small><p>沉淀的学习笔记</p></div></div><section id="projects"><div class="section-head"><h2>项目进行时</h2><small>从理解原理，到亲手实现</small></div><div class="projects">${card('rag')}${card('rl')}</div></section><section id="next"><div class="section-head"><h2>下一步，先做一件小事</h2></div><div class="callout">${total()===12?'回顾实验结果，整理下一轮迭代计划。':'选择一条路线，完成第一个最小实验。'}<small>路线是可调整的起点。每完成一个阶段，勾选进度，再记录你的发现。</small></div></section><section id="recent"><div class="section-head"><h2>最近的学习记录</h2><a class="muted" href="#journal">全部笔记 ↗</a></div>${notesView(state.notes.slice(0,3))}</section>`;toc=[['projects','项目进行时'],['next','下一步计划'],['recent','最近的学习记录']]}
else if(tracks[route]){let t=tracks[route];html=renderHeading(t.title,'PROJECT / '+(route==='rag'?'01':'02'),t.desc)+`<div class="meta"><span>规划路线 · 可按实际项目调整</span><span>${count(route)} / 6 阶段已完成</span></div><progress value="${count(route)}" max="6" aria-label="项目完成进度"></progress><div class="callout">${route==='rag'?'项目目标：构建一个会检索、会引用、可评测的知识助手。':'项目目标：跑通一个小规模 Agent 训练实验，或完成一次论文复现。'}<small>完成阶段后勾选下方任务；实验配置、结果与问题可以记录在笔记中。</small></div>`;t.phases.forEach((p,i)=>{html+=`<section id="phase${i}"><div class="section-head"><h2>0${i+1}　${p[0]}</h2></div><div class="steps">${p[1].map((x,j)=>{let id=route+'-'+(i*2+j);return `<label class="step"><input type="checkbox" data-step="${id}" ${state.done[id]?'checked':''}><div><strong>${x[0]}</strong><p>${x[1]}</p></div></label>`}).join('')}</div></section>`;toc.push(['phase'+i,p[0]])});html+=`<section id="track-notes"><div class="section-head"><h2>项目笔记</h2></div>${notesView(state.notes.filter(n=>n.track===t.title))}</section>`;toc.push(['track-notes','项目笔记'])}
else if(route==='journal'){html=renderHeading('学习日志','NOTES / SMALL STEPS, REAL PROGRESS','记录理解、保留问题，也为每一次实验留下可追溯的线索。')+`<div class="section-head"><select id="filter" class="filter" aria-label="按方向筛选"><option>全部</option><option>Agentic RAG</option><option>Agentic RL</option><option>学习随记</option></select><div class="toolbar"><button class="secondary" id="export">导出备份</button><button class="secondary" id="import">导入备份</button><input id="file" type="file" accept="application/json" hidden></div></div><div id="entries">${notesView(state.notes.filter(n=>filter==='全部'||n.track===filter))}</div><p class="muted">笔记和进度仅保存在当前浏览器，不会自动同步到其他设备。建议定期导出备份。</p>`;toc=[['entries','全部记录']]}
else{html=renderHeading('关于这个空间','ABOUT / ZXY','你好，我是 zxy。这里记录我学习和实践 Agent 开发的过程。',false)+'<div class="callout">两条主线，一个持续积累的知识空间。<small>Agentic RAG：让 Agent 更好地使用知识。<br>Agentic RL：在环境交互与反馈中改进 Agent。</small></div><section id="method"><div class="section-head"><h2>我的记录方式</h2></div><p>先建立一个能运行的基线，再提出问题、设计实验、比较结果。每篇笔记都可以记录：学到了什么、证据是什么、哪里还不确定，以及下一步准备做什么。</p></section><section id="data"><div class="section-head"><h2>数据与备份</h2></div><p>这个空间的笔记与进度保存在当前浏览器。更换设备或清理浏览器数据前，请在学习日志中导出 JSON 备份；导入备份可以合并笔记和已完成的进度。</p></section>';toc=[['method','记录方式'],['data','数据与备份']]}
$('#main').innerHTML=html+footer();$('#toc').innerHTML=toc.map(x=>`<a href="#${x[0]}">${x[1]}</a>`).join('');document.title=(tracks[route]?.title||({overview:'学习总览',journal:'学习日志',about:'关于'}[route]))+' · zxy-note';if($('#filter'))$('#filter').value=filter;}
function openNote(id){editing=id||null;const n=state.notes.find(n=>n.id===id),form=$('#note-form');form.reset();form.elements.date.value=n?.date||new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,10);form.elements.title.value=n?.title||'';form.elements.body.value=n?.body||'';form.elements.track.value=n?.track||tracks[location.hash.slice(1)]?.title||'学习随记';$('#editor').showModal();form.elements.title.focus()}
document.addEventListener('click',e=>{if(e.target.closest('[data-new]'))openNote();if(e.target.dataset.edit)openNote(e.target.dataset.edit);if(e.target.dataset.delete&&confirm('删除这篇笔记？此操作无法撤销。')){state.notes=state.notes.filter(n=>n.id!==e.target.dataset.delete);save();render()}if(e.target.id==='export'){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({version:1,...state},null,2)],{type:'application/json'}));a.download='zxy-notes-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}if(e.target.id==='import')$('#file').click()});
document.addEventListener('change',async e=>{if(e.target.dataset.step){state.done[e.target.dataset.step]=e.target.checked;save();render()}if(e.target.id==='filter'){filter=e.target.value;render()}if(e.target.id==='file'){try{let d=JSON.parse(await e.target.files[0].text());if(d.version!==1||!Array.isArray(d.notes)||!d.done||!d.notes.every(n=>['id','title','body','date','track'].every(k=>typeof n[k]==='string')))throw Error();let map=new Map(state.notes.map(n=>[n.id,n]));d.notes.forEach(n=>{if(!map.has(n.id))map.set(n.id,n)});state.notes=[...map.values()].sort((a,b)=>b.date.localeCompare(a.date));Object.keys(d.done).forEach(k=>{if(/^(rag|rl)-[0-5]$/.test(k)&&d.done[k]===true)state.done[k]=true});save();render();toast('备份已合并')}catch{toast('无法导入，请选择有效的 zxy 笔记备份')}}});
$('#note-form').addEventListener('submit',e=>{e.preventDefault();const f=e.target.elements;if(!f.title.value.trim()||!f.body.value.trim()){toast('请填写标题和笔记内容');return}let n={id:editing||crypto.randomUUID(),title:f.title.value.trim(),body:f.body.value.trim(),date:f.date.value,track:f.track.value};state.notes=state.notes.filter(x=>x.id!==n.id);state.notes.push(n);state.notes.sort((a,b)=>b.date.localeCompare(a.date));const ok=save();$('#editor').close();render();if(ok)toast('笔记已保存')});$('#close').onclick=()=>$('#editor').close();$('#theme').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';save();document.body.classList.toggle('dark',state.theme==='dark')};$('#menu').onclick=()=>$('.sidebar').classList.toggle('open');window.addEventListener('hashchange',()=>{render();if(['overview','rag','rl','journal','about'].includes(location.hash.slice(1)))window.scrollTo(0,0)});render();
